name: stack

on:
  push:
    branches: [ci-stack, wip/ghc-lib]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.4"]
        ghc:
          - "8.2.2"
          - "8.4.4"
          - "8.6.5"
          - "8.8.4"
          - "8.10.7"
          - "9.0.1"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: haskell/actions/setup@v1
      name: Setup Stack
      with:
        enable-stack: true
        stack-version: 'latest'
        cabal-version: ${{ matrix.cabal }}

    - uses: haskell/actions/hlint-setup@v2
      name: Set up HLint

    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: build
      run: stack build --no-terminal --stack-yaml=./stack/stack-${{ matrix.ghc }}.yaml

    - uses: haskell/actions/hlint-run@v2
      name: hlint
      with:
        path: .
        fail-on: suggestion
